export const ARTICLE_SEARCH = "ARTICLE_SEARCH";
export const ARTICLE_SEARCH_RESPONSE = "ARTICLE_SEARCH_RESPONSE";

export const SET_CURRENT_SEARCH_TERM = "SET_CURRENT_SEARCH_TERM";

export const SEARCHING = "SEARCHING";

export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const UNSAVE_ARTICLE = "UNSAVE_ARTICLE";

export const BOOKMARK_ARTICLE = "BOOKMARK_ARTICLE";
export const REMOVE_BOOKMARKED_ARTICLE = "REMOVE_BOOKMARKED_ARTICLE";


