export const ARTICLE_SEARCH_RESPONSE = "ARTICLE_SEARCH_RESPONSE";
export const ARTICLE_SEARCH = "ARTICLE_SEARCH";
export const SET_CURRENT_SEARCH_TERM = "SET_CURRENT_SEARCH_TERM";
export const SEARCHING = "SEARCHING";
